### ISSUE TITLE
migration

### ISSUE THREAD

**Issue by margueritech** [gdarquie/mc2#31]
ajouter pour chaque number qui n'a pas de director, celui du film

**Comment by gdarquie** [comment]
INSERT INTO number_has_director
    (
     SELECT n.number_id as number_id, r.person_id as person_id FROM film f
  INNER JOIN number n ON n.film_id = f.film_id
  INNER JOIN film_has_director r ON r.film_id = f.film_id
  WHERE n.number_id IN (
      SELECT n.number_id FROM number n
        LEFT JOIN number_has_director r ON r.number_id = n.number_id
        WHERE r.number_id is null
      )
    );
